// Part: LEGO 2x4 Brick
// Description: Standard LEGO-compatible 2x4 brick with studs and underside tubes
// Author: Generated by Claude Code
// Units: mm

// === Parameters ===
stud_pitch    = 8.0;     // center-to-center stud spacing
studs_x       = 4;       // studs along length
studs_y       = 2;       // studs along width

brick_length  = studs_x * stud_pitch - 0.2;  // 31.8mm
brick_width   = studs_y * stud_pitch - 0.2;  // 15.8mm
brick_height  = 11.4;    // standard brick height (3 plates)

wall          = 1.5;     // outer wall thickness
floor_t       = 1.0;     // bottom floor thickness

stud_d        = 4.8;     // stud diameter
stud_h        = 1.8;     // stud height above brick top

tube_od       = 6.51;    // underside tube outer diameter
tube_id       = 4.8;     // underside tube inner diameter

tol           = 0.1;     // print tolerance per side

// === Resolution ===
$fn = 64;

// === Modules ===

// Single stud on top
module stud() {
    cylinder(d = stud_d, h = stud_h);
}

// Grid of studs on top surface
module stud_grid() {
    for (ix = [0 : studs_x - 1])
        for (iy = [0 : studs_y - 1])
            translate([
                stud_pitch/2 + ix * stud_pitch,
                stud_pitch/2 + iy * stud_pitch,
                brick_height
            ])
            stud();
}

// Single underside tube (hollow cylinder for clutch)
module tube() {
    difference() {
        cylinder(d = tube_od, h = brick_height - floor_t);
        translate([0, 0, -0.01])
            cylinder(d = tube_id, h = brick_height - floor_t + 0.02);
    }
}

// Grid of underside tubes (between studs)
module tube_grid() {
    if (studs_x > 1 && studs_y > 1) {
        for (ix = [0 : studs_x - 2])
            for (iy = [0 : studs_y - 2])
                translate([
                    stud_pitch + ix * stud_pitch,
                    stud_pitch + iy * stud_pitch,
                    floor_t
                ])
                tube();
    }
}

// Hollow brick shell
module brick_shell() {
    difference() {
        // Outer block
        cube([brick_length, brick_width, brick_height]);

        // Hollow interior
        translate([wall, wall, floor_t])
            cube([
                brick_length - 2 * wall,
                brick_width  - 2 * wall,
                brick_height - floor_t + 0.01
            ]);
    }
}

// === Complete Brick ===
module lego_2x4_brick() {
    brick_shell();
    stud_grid();
    tube_grid();
}

// === Render ===
lego_2x4_brick();
