// Part: MagSafe Mountain Stand (Version B - Portrait + Landscape)
// Description: Mountain/rock-themed MagSafe charger stand with cross,
//              open book detail, coin tray, and cable routing.
//              No phone lip — MagSafe magnet holds phone directly.
// Author: Generated by Claude Code
// Units: mm
// Printer: Flashforge AD5X (build: 220x220x220)

// =============================================
// === Parameters ===
// =============================================

// --- Base ---
base_d         = 130;    // base platform diameter
base_h         = 8;      // base platform height
base_chamfer   = 2;      // chamfer on base edge

// --- Mountain Body ---
mtn_h          = 95;     // mountain height from base top
mtn_base_rx    = 50;     // mountain base radius X (half of width)
mtn_base_ry    = 40;     // mountain base radius Y (half of depth)
mtn_peak_offset= -5;     // peak offset toward back (negative = back)
mtn_roughness  = 8;      // number of radial bumps for rock texture

// --- MagSafe Pocket ---
ms_puck_d      = 56.0;   // Apple MagSafe puck diameter
ms_pocket_d    = 57.0;   // pocket diameter (puck + 1mm clearance)
ms_pocket_depth= 6.5;    // pocket depth (puck 5.65mm + clearance)
ms_center_h    = 55;     // center of puck height from base top
ms_tilt        = 75;     // tilt angle from horizontal (75° = leaning back 15°)

// --- Cable Channel ---
cable_d        = 5.0;    // cable channel diameter
cable_exit_h   = 5;      // cable exit height at back of base

// --- Cross ---
cross_h        = 25;     // total cross height
cross_arm_w    = 15;     // horizontal arm width
cross_bar      = 3.0;    // bar thickness (square cross-section)
cross_arm_h    = 17;     // height where horizontal arm sits

// --- Coin Tray ---
tray_w         = 30;     // width
tray_d         = 20;     // depth
tray_h         = 8;      // recess depth
tray_r         = 3;      // corner radius
tray_offset_x  = -35;    // offset from center (left side)
tray_offset_y  = -15;    // offset forward

// --- Book ---
book_w         = 35;     // book width (open spread)
book_d         = 25;     // book depth
book_h         = 4;      // book thickness
book_offset_x  = 10;     // offset from center
book_offset_y  = -30;    // offset forward (front of base)

// --- Resolution ---
$fn = 64;

// =============================================
// === Modules ===
// =============================================

// --- Chamfered Base Platform ---
// Color 1: Stone/Sand
module base_platform() {
    // Color: 1 (stone/sand)
    hull() {
        // Main cylinder
        translate([0, 0, base_chamfer])
            cylinder(d = base_d, h = base_h - base_chamfer);
        // Chamfered bottom edge
        cylinder(d = base_d - 2*base_chamfer, h = 0.01);
    }
}

// --- Mountain Body ---
// Simplified rock form using scaled sphere + noise-like bumps
// Color 1: Stone/Sand
module mountain_body() {
    // Color: 1 (stone/sand)

    // Main mountain cone/dome shape
    hull() {
        // Base ellipse
        translate([0, 0, 0])
            scale([mtn_base_rx*2/base_d, mtn_base_ry*2/base_d, 1])
            cylinder(d = base_d, h = 1);

        // Peak
        translate([mtn_peak_offset, 0, mtn_h])
            sphere(d = 12);
    }

    // Rock texture bumps (radial protrusions)
    for (i = [0 : mtn_roughness - 1]) {
        angle = i * 360 / mtn_roughness;
        bump_h = mtn_h * (0.3 + 0.4 * abs(sin(angle * 3.7 + 45)));
        bump_r = 8 + 6 * abs(cos(angle * 2.3 + 30));
        bump_dist = mtn_base_rx * 0.6;

        hull() {
            translate([bump_dist * cos(angle) * 0.7, bump_dist * sin(angle) * 0.7, 0])
                cylinder(r = bump_r, h = 1);
            translate([
                bump_dist * cos(angle) * 0.3 + mtn_peak_offset * 0.5,
                bump_dist * sin(angle) * 0.2,
                bump_h
            ])
                sphere(r = bump_r * 0.4);
        }
    }

    // Extra rock clusters on the sides
    for (i = [0 : 5]) {
        angle = i * 60 + 15;
        h_pos = mtn_h * (0.2 + 0.3 * abs(sin(angle * 2)));
        r_pos = mtn_base_rx * (0.5 + 0.2 * cos(angle));

        translate([r_pos * cos(angle) * 0.6, r_pos * sin(angle) * 0.5, h_pos])
            scale([1, 0.8, 1.2])
            sphere(d = 12 + 4 * sin(angle * 3));
    }
}

// --- MagSafe Pocket (cutout) ---
module magsafe_pocket() {
    // Position: centered on front face of mountain, tilted back
    translate([0, -mtn_base_ry * 0.5, base_h + ms_center_h])
        rotate([-90 + (90 - ms_tilt), 0, 0])
        union() {
            // Main puck recess (circular pocket)
            cylinder(d = ms_pocket_d, h = ms_pocket_depth + 1);

            // Cable exit slot (bottom of puck)
            translate([0, -ms_pocket_d/2 + 3, 0])
                cylinder(d = cable_d + 1, h = ms_pocket_depth + 20);
        }
}

// --- Cable Channel (cutout) ---
module cable_channel() {
    // Route from MagSafe pocket down through mountain and out the back
    // Vertical section behind puck
    translate([0, -mtn_base_ry * 0.3, base_h])
        cylinder(d = cable_d, h = ms_center_h);

    // Horizontal exit through back of base
    translate([0, 0, base_h + cable_exit_h])
        rotate([-90, 0, 0])
        cylinder(d = cable_d, h = mtn_base_ry + 20);

    // Exit slot in base bottom
    translate([0, mtn_base_ry * 0.5, 0])
        cylinder(d = cable_d, h = base_h + cable_exit_h + 1);
}

// --- Cross ---
// Color 2: Gold
module cross() {
    // Color: 2 (gold)
    translate([mtn_peak_offset, 0, base_h + mtn_h]) {
        // Vertical bar
        translate([-cross_bar/2, -cross_bar/2, 0])
            cube([cross_bar, cross_bar, cross_h]);

        // Horizontal bar
        translate([-cross_arm_w/2, -cross_bar/2, cross_arm_h])
            cube([cross_arm_w, cross_bar, cross_bar]);
    }
}

// --- Coin Tray (cutout from base/mountain) ---
module coin_tray_cutout() {
    translate([tray_offset_x, tray_offset_y, base_h - 0.01]) {
        // Rounded rectangle pocket
        hull() {
            translate([tray_r, tray_r, 0])
                cylinder(r = tray_r, h = tray_h + 0.02);
            translate([tray_w - tray_r, tray_r, 0])
                cylinder(r = tray_r, h = tray_h + 0.02);
            translate([tray_r, tray_d - tray_r, 0])
                cylinder(r = tray_r, h = tray_h + 0.02);
            translate([tray_w - tray_r, tray_d - tray_r, 0])
                cylinder(r = tray_r, h = tray_h + 0.02);
        }
    }
}

// --- Open Book ---
// Color 3: Brown (cover) + white (pages)
module open_book() {
    // Color: 3 (brown/tan)
    translate([book_offset_x, book_offset_y, base_h]) {
        // Left page
        translate([-book_w/2, 0, 0])
            rotate([0, 5, 0])  // slight angle for open book look
            cube([book_w/2 - 1, book_d, book_h]);

        // Right page
        translate([1, 0, 0])
            rotate([0, -5, 0])
            cube([book_w/2 - 1, book_d, book_h]);

        // Spine
        translate([-1, 0, 0])
            cube([2, book_d, book_h + 1]);
    }
}

// =============================================
// === Assembly ===
// =============================================

module magsafe_mountain_stand() {
    difference() {
        union() {
            // Base platform
            base_platform();

            // Mountain body (sitting on base)
            translate([0, 5, base_h])
                mountain_body();

            // Open book (decorative, on base)
            open_book();
        }

        // Subtract: MagSafe pocket
        magsafe_pocket();

        // Subtract: Cable channel
        cable_channel();

        // Subtract: Coin tray
        coin_tray_cutout();

        // Trim everything below z=0
        translate([-base_d, -base_d, -base_d])
            cube([base_d * 2, base_d * 2, base_d]);

        // Trim to base diameter (clean circle)
        difference() {
            translate([-base_d, -base_d, -0.01])
                cube([base_d * 2, base_d * 2, base_h + 0.02]);
            cylinder(d = base_d, h = base_h + 0.04);
        }
    }

    // Cross (added after boolean ops so it doesn't get cut)
    cross();
}

// === Render ===
magsafe_mountain_stand();

// === Build Notes ===
// Total dimensions: ~130mm diameter x ~128mm tall (fits AD5X: 220x220x220)
// Print orientation: Upright (base down)
// Supports: Required for MagSafe pocket overhang
// Multi-color zones:
//   Color 1 (stone/sand): Base + Mountain body
//   Color 2 (gold): Cross
//   Color 3 (brown): Book
//   Color 4 (gold accent): Coin tray rim (optional)
